language: python
python:
  - 3.5

# addons:
#   apt:
#     packages:
#       - build-essential
#       - gcc
#       - g++
#       - gfortran
#       - mpich
#       - valgrind
#       - bison
#       - flex
#       - cmake
#       - libtool
#       - autoconf
#       - perl
#       - m4
#       - git
#       - liblapack-dev
#       - liblapack-doc
#       - liblapack3gf
#       - libblas-dev
#       - libblas-doc
#       - libblas3gf

cache:
  directories:
    - $HOME/conda
    # - $HOME/petsc_and_slepc_4py

install:
  - bash deps/travis-install-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - source activate test-environment
  - conda list
  - pip install --no-deps .
  # - bash deps/travis-install-slepc4py.sh

script:
  - py.test

after_success:
  - coveralls
