language: python
python:
  - 3.5

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - gfortran
      - valgrind
      - bison
      - flex
      - cmake
      - libtool
      - autoconf
      - perl
      - m4
      - git
      - liblapack-dev
      - liblapack3gf
      - libblas-dev
      - libblas3gf

cache:
  directories:
    - $HOME/conda
    - $HOME/petsc_and_slepc

before_install:
  - bash deps/travis-install-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - source activate test-environment
  - bash deps/travis-install-openmpi.sh
  - export PATH="$HOME/local/bin:$PATH"
  - bash deps/travis-install-slepc4py.sh

install:
  - pip install .

script:
  - export OMP_NUM_THREADS=2
  - py.test

after_success:
  - coveralls
  - codecov
  - codeclimate-test-reporter
