language: python
python:
  - 3.5
dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - gfortran
      - valgrind
      - bison
      - flex
      - cmake
      - libtool
      - autoconf
      - perl
      - m4
      - git
      - liblapack-dev
      - liblapack3gf
      - libblas-dev
      - libblas3gf
      - wget

cache:
  directories:
    - $HOME/conda
    - $HOME/petsc_and_slepc

before_install:
  - function chronic { /bin/rm --force /tmp/surpress.out 2> /dev/null; $* 2>&1 > /tmp/surpress.out || cat /tmp/surpress.out; /bin/rm /tmp/surpress.out; }
  - chronic bash deps/travis-install-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - source activate test-environment
  - chronic bash deps/travis-install-openmpi.sh
  - mpiexec --version
  - mpiexec -np 2 hostname
  - chronic bash deps/travis-install-slepc4py.sh

install:
  - pip install .

script:
  - export OMP_NUM_THREADS=2
  - py.test

after_success:
  - coveralls
  - codecov
  - codeclimate-test-reporter
  - python-codacy-coverage -r coverage.xml
