language: python
python:
  - 3.5
dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - gfortran
      - valgrind
      - bison
      - flex
      - cmake
      - libtool
      - autoconf
      - perl
      - m4
      - git
      - liblapack-dev
      - liblapack3gf
      - libblas-dev
      - libblas3gf
      - wget

cache:
  directories:
    - $HOME/conda
    - $HOME/petsc_and_slepc
    - $HOME/mpi_stuff
  timeout: 1000

before_install:
  - function chronic { /bin/rm --force /tmp/surpress.out 2> /dev/null; $* 2>&1 > /tmp/surpress.out || cat /tmp/surpress.out; /bin/rm /tmp/surpress.out; }
  - chronic bash deps/travis-install-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - source activate test-environment
  - export PATH="$HOME/mpi_stuff/openmpi_install/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/mpi_stuff/openmpi_install/lib:$LD_LIBRARY_PATH"
  - "if [ ${BUILD_MPI:-ON} = ON ]; then chronic bash deps/travis-install-openmpi.sh; fi"
  - mpiexec --version
  - mpiexec -np 2 hostname
  - "if [ ${BUILD_SLEPC:-ON} = ON ]; then chronic bash deps/travis-install-slepc4py.sh; fi"

install:
  - pip install -U --no-deps .

script:
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then export OMP_NUM_THREADS=2; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then env COVERAGE_FILE=.coverage.autompi pytest; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then env COVERAGE_FILE=.coverage.manualmpi quimb-mpi-python --np 2 -m pytest; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then coverage combine .; fi"

after_success:
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then coveralls; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then codecov; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then codeclimate-test-reporter; fi"
  - "if [ ${TEST_QUIMB:-ON} = ON ]; then python-codacy-coverage -r coverage.xml; fi"
