language: python
python: 3.5

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - gfortran
      - mpich
      - valgrind
      - bison
      - flex
      - cmake
      - libtool
      - autoconf
      - perl
      - m4
      - git

cache:
  directories:
    - $HOME/petsc_and_slepc_4py

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy numba numexpr coverage
  - source activate test-environment
  - python setup.py install
  - pip install pytest-cov coveralls
  - chmod -X deps/travis-install-slepc4py.sh
  - ./deps/travis-install-slepc4py.sh
  - pip install .

script:
  - py.test

after_success:
  - coveralls
